flowchart TD
    subgraph App1["App 1 - Session Registration"]
        A1[Engineer registers interest to host a session]
        B1[Guild editors review the request]
        C1[Editors communicate with engineer to understand more]
        D1[Editors approve,reject the guild topic]
        E1[Engineer proposes a closest date for the session]
        A1 --> B1
        B1 --> C1
        C1 --> D1
        D1 --> E1
    end

    subgraph App2["App 2 - Session Management"]
        A2[Organizer manages sessions in dashboard portal]
        B2[Date confirmed and notification sent to engineer]
        C2[Engineer accepts and profile pushed to speakers board]
        D2[App books a room, publishes sessions, and sends RSVP]
        E2[App sends reminders and updates to RSVP attendees]
        F2[Attendees receive additional info about the session and speaker]
        A2 --> B2
        B2 --> C2
        C2 --> D2
        D2 --> E2
        E2 --> F2
    end

    subgraph App3["App 3 - Background Tasks"]
        A3[Provide basic PPT templates, documents, images, resources]
        B3[Request for co-host to help speakers from editors]
        C3[Gather finalized sessions documents,resources for editors]
        D3[Trigger survey to participants after sessions]
        E3[Propose high-scored sessions to be posted in guild blog]
        A3 --> B3
        B3 --> C3
        C3 --> D3
        D3 --> E3
    end

    subgraph App4["App 4 - Speaker & Session Details"]
        A4[Speakers provide more details on their sessions]
        B4[Editors assign co-hosts to sessions]
        C4[Participants receive session resources (invitations,SWAGs)]
        D4[Editors score the session based on quality and survey]
        E4[Speakers receive statistics on their profiles]
        F4[PowerBI reports and dashboards for statistics]
        A4 --> B4
        B4 --> C4
        C4 --> D4
        D4 --> E4
        E4 --> F4
    end

    App1 --> App2 --> App3 --> App4
